name: Changelog
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate a changelog
        run: bgord-scripts/changelog-generate.sh

      - name: Print changelog
        run: cat infra/CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: "docs: generate CHANGELOG"
          file_pattern: infra/CHANGELOG.md
